#!/bin/bash

readonly PROGNAME=$(basename $0)
readonly ARGS="$@"

usage() {
    cat <<- EOF
	Usage: $PROGNAME FILE

	Returns the file size in bytes.
	EOF
}

# $1 - file name
main() {
    local file_name="$1"
    local size

    is file "${file_name}" || return 0

    size=$(wc -w <"${file_name}")

    echo "${size}"
}


main $ARGS
