#!/bin/bash

readonly PROGNAME=$(basename "$0")
readonly ARGS=("$@")

usage() {
    cat <<- EOF
	Usage: ${PROGNAME} FILE

	Returns the file size in bytes.
	EOF
}

# $1 - file name
main() {
    local filename=$1
    local size

    is file "${filename}" || return 0

    size=$(wc -w <"${filename}")

    echo "${size}"
}


main "${ARGS[0]}"
